from quiz.ui import cyan, bold


def get_help_text() -> str:
    lines = [
        cyan(bold("=" * 60)),
        cyan(bold("QUIZ PROGRAM HELP")),
        cyan(bold("=" * 60)),
        "",
        cyan(bold("Available commands:")),
        "/help",
        "    Show this help menu.",
        "/quizzes",
        "    Show all registered quiz files.",
        "/register <path_to_csv>",
        "    Copy a CSV quiz file into the program's quizzes folder.",
        "/start quizname.csv -a",
        "    Start a quiz and ask all questions.",
        "/start quizname.csv -w",
        "    Start a quiz and ask only previously wrong questions.",
        "/exit",
        "    Exit the program.",
        "",
        cyan(bold("During a quiz:")),
        "/quit",
        "    Stop the current quiz and return to the main menu.",
        "",
        cyan(bold("How to create a quiz CSV file:")),
        "Your CSV file must use these exact headers:",
        "question;options;correct",
        "",
        cyan(bold("Format rules:")),
        "- Use ';' to separate the CSV columns.",
        "- Use '|' to separate answer options inside the options field.",
        "- Use '|' in the correct field for multiple correct answers.",
        "- Leave the correct field empty if none of the listed answers is correct.",
        "",
        cyan(bold("Examples:")),
        "question;options;correct",
        "What is the capital of France?;Berlin|Madrid|Paris|Rome;3",
        "Which are programming languages?;Python|Banana|Java|Table|C++;1|3|5",
        "Which numbers are even?;1|2|3|4|5|6;2|4|6",
        "Which of these numbers is greater than 10?;1|2|3|4;",
        "",
        cyan(bold("Answer input:")),
        "- For one correct answer: enter one number",
        "  Example: 3",
        "- For multiple correct answers: enter all numbers separated by spaces",
        "  Example: 1 3 5",
        "- If none of the answers is correct: press Enter without typing anything",
        "",
        cyan(bold("Important:")),
        "- The first row must be the header row.",
        "- Each following row is one question.",
        "- You can use commas freely inside your question text.",
        "- If an option itself contains '|', that would break the format.",
        "- Wrong answers are saved automatically for each quiz file.",
        "",
        cyan(bold("Typical workflow:")),
        "1. Create a CSV file.",
        "2. Register it with /register <path_to_csv>",
        "3. View available quizzes with /quizzes",
        "4. Start one with /start quizname.csv -a",
        "5. Later review mistakes with /start quizname.csv -w",
        "",
        cyan(bold("=" * 60)),
    ]
    return "\n".join(lines)