from quiz.ui import cyan, bold


def get_help_text() -> str:
    lines = [
        cyan(bold("=" * 60)),
        cyan(bold("QUIZ PROGRAM HELP")),
        cyan(bold("=" * 60)),
        "",
        cyan(bold("Available commands:")),
        "/help",
        "    Show this help menu.",
        "/quizzes",
        "    Show all registered quiz files.",
        "/register <path_to_csv>",
        "    Copy a CSV quiz file into the program's quizzes folder.",
        "/create <quizname>",
        "    Create a new quiz interactively and save it as a CSV file.",
        "/start quizname.csv -a",
        "    Start a quiz and ask all questions.",
        "/start quizname.csv -w",
        "    Start a quiz and ask only previously wrong questions.",
        "/exit",
        "    Exit the program.",
        "",
        cyan(bold("During a quiz:")),
        "/quit",
        "    Stop the current quiz and return to the main menu.",
        "",
        cyan(bold("CSV format:")),
        "Your CSV file must use these exact headers:",
        "type;question;options;correct",
        "",
        cyan(bold("Supported question types:")),
        "- multiplechoice",
        "- text",
        "",
        cyan(bold("multiplechoice rules:")),
        "- Use ';' to separate columns.",
        "- Use '|' to separate options inside the options field.",
        "- Use numbers in 'correct', e.g. 2 or 1|3|4",
        "- Leave 'correct' empty if none of the listed options is correct.",
        "",
        cyan(bold("text rules:")),
        "- Leave the options field empty.",
        "- Put the expected answer tokens into 'correct', separated by '|'.",
        "- Word order in the user's answer does not matter.",
        "- Upper/lower case does not matter.",
        "",
        cyan(bold("Examples:")),
        "type;question;options;correct",
        "multiplechoice;What is the capital of France?;Berlin|Madrid|Paris|Rome;3",
        "multiplechoice;Which numbers are even?;1|2|3|4|5|6;2|4|6",
        "multiplechoice;Which of these numbers is greater than 10?;1|2|3|4;",
        'text;Give the irregular verb forms of "go" in English;;go|went|gone',
        "text;Name the primary colors;;red|blue|yellow",
        "",
        cyan(bold("Answer input:")),
        "- Multiple choice, one correct answer: 3",
        "- Multiple choice, multiple correct answers: 1 3 5",
        "- Multiple choice, none correct: press Enter",
        "- Text question example: go went gone",
        "- Text answer word order does not matter",
        "",
        cyan(bold("Important:")),
        "- The first row must be the header row.",
        "- Each following row is one question.",
        "- You can use commas freely inside your question text.",
        "- If an option itself contains '|', that would break the format.",
        "- Wrong answers are saved automatically for each quiz file.",
        "",
        cyan(bold("Typical workflow:")),
        "1. Create a CSV file.",
        "2. Register it with /register <path_to_csv>",
        "3. Either create one with /create <quizname> or register one with /register <path_to_csv>",
        "4. View available quizzes with /quizzes",
        "5. Start one with /start quizname.csv -a",
        "6. Later review mistakes with /start quizname.csv -w",
        "",
        cyan(bold("=" * 60)),
    ]
    return "\n".join(lines)