from quiz.ui import cyan, bold, horizontal_rule


def get_help_text() -> str:
    lines = [
        cyan(bold(horizontal_rule("="))),
        cyan(bold("QUIZ PROGRAM HELP")),
        cyan(bold(horizontal_rule("="))),
        "",
        cyan(bold("Available commands:")),
        "/help",
        "    Show this help menu.",
        "/quizzes",
        "    Show all registered quiz files.",
        "/register <path_to_csv>",
        "    Copy a CSV quiz file into the program's quizzes folder.",
        "/create <quizname>",
        "    Create a new quiz interactively and save it as a CSV file.",
        "/start quizname.csv -a",
        "    Start a quiz and ask all questions.",
        "/start quizname.csv -w",
        "    Start a quiz and ask only previously wrong questions.",
        "/exit",
        "    Exit the program.",
        "",
        cyan(bold("During a quiz:")),
        "/quit",
        "    Stop the current quiz and return to the main menu.",
        "After answering a question:",
        "    Press Enter to continue to the next question.",
        "    Or type a follow-up question to ask the local AI about the current quiz question.",
        "If local AI is not available:",
        "    The program can offer to open the Ollama download page",
        "    or try an automatic installation with winget.",
        "",
        cyan(bold("CSV format:")),
        "Your CSV file must use these exact headers:",
        "type;question;options;correct",
        "",
        cyan(bold("Supported question types:")),
        "- multiplechoice",
        "- text",
        "- sentence",
        "",
        cyan(bold("General CSV rules:")),
        "- Use ';' to separate the four columns.",
        "- The first row must be the header row.",
        "- Each following row is one question.",
        "- You can use commas freely inside question text.",
        "- If an option itself contains '|', that breaks the format.",
        "",
        cyan(bold("multiplechoice rules:")),
        "- Use '|' to separate options inside the options field.",
        "- In 'correct', use answer numbers such as 2 or 1|3|4.",
        "- Leave 'correct' empty if none of the listed options is correct.",
        "",
        cyan(bold("text rules (unordered tokens):")),
        "- Leave the options field empty.",
        "- Put the expected answer tokens into 'correct', separated by '|'.",
        "- Word order in the user's answer does not matter.",
        "- Upper/lower case does not matter.",
        "- Use this for token-style answers such as irregular verbs, keywords, or short vocabulary sets.",
        "",
        cyan(bold("sentence rules (ordered full sentence):")),
        "- Leave the options field empty.",
        "- Put one full correct sentence into 'correct'.",
        "- If multiple full phrasings should be accepted, separate them with '|'.",
        "- Word order matters.",
        "- Upper/lower case does not matter.",
        "- Minor spacing differences are ignored.",
        "- Use this for translations, grammar exercises, and full sentence production.",
        "",
        cyan(bold("When to use which type:")),
        '- Use "text" for answers like: go went gone',
        '- Use "text" for answers like: red blue yellow',
        '- Use "sentence" for answers like: You should have given first aid immediately.',
        "",
        cyan(bold("Examples:")),
        "type;question;options;correct",
        "multiplechoice;What is the capital of France?;Berlin|Madrid|Paris|Rome;3",
        "multiplechoice;Which numbers are even?;1|2|3|4|5|6;2|4|6",
        "multiplechoice;Which of these numbers is greater than 10?;1|2|3|4;",
        'text;Give the irregular verb forms of "go" in English;;go|went|gone',
        "text;Name the primary colors;;red|blue|yellow",
        'sentence;Turn this German sentence into an English sentence: Du hättest sofort Erste Hilfe leisten sollen.;;you should have given first aid immediately|you should have provided first aid immediately',
        'sentence;Translate into English: Er hätte früher gehen sollen.;;he should have left earlier',
        "",
        cyan(bold("Answer input:")),
        "- Multiple choice, one correct answer: 3",
        "- Multiple choice, multiple correct answers: 1 3 5",
        "- Multiple choice, none correct: press Enter",
        "- Text example: go went gone",
        "- Text answer word order does not matter",
        "- Sentence example: you should have given first aid immediately",
        "- Sentence answer word order matters",
        "",
        cyan(bold("Important:")),
        "- Wrong answers are saved automatically for each quiz file.",
        "- For text questions, do not use full sentences unless word order truly does not matter.",
        "- For sentence questions, write full accepted answer sentences in the correct field.",
        "- If a sentence question has several valid phrasings, separate them with '|'.",
        "",
        cyan(bold("Typical workflow:")),
        "1. Create a CSV file.",
        "2. Register it with /register <path_to_csv> or copy the .csv file into the quizzes folder.",
        "3. View available quizzes with /quizzes.",
        "4. Start one with /start quizname.csv -a.",
        "5. Later review mistakes with /start quizname.csv -w.",
        "",
        cyan(bold(horizontal_rule("="))),
    ]
    return "\n".join(lines)